services:
  sample_pgdb:
    container_name: sampletutorialdb
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - "5436:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  sample_go_app:
    container_name: sample_go_app
    build: 
      dockerfile: Dockerfile
      context: .
    environment:
      DB_HOST: sample_pgdb
      DB_USER: admin
      DB_PASS: admin
      DB_NAME: postgres
      DB_PORT: 5432
      type: postgres
    ports:
      - "8500:8500"
    depends_on:
      sample_pgdb:
        condition: service_healthy
    restart: always
